### ISSUE TITLE
Getting Error in sample.py file 

### ISSUE THREAD

**Issue by himabinduyeddala** [inikdom/neural-chatbot#22] opened 2017-11-09 06:44 UTC
HI inikdom,
   My stack is-
       python -3.6
       tensorflow -1.2
       pycharm IDE- 2017
 I am getting  following error while running sample.py file (specified checkpoint dir and data dir) ---

Traceback (most recent call last):
  File "sample.py", line 101, in <module>
    main()
  File "sample.py", line 32, in main
    model = load_model(sess, FLAGS.checkpoint_dir)
  File "sample.py", line 78, in load_model
    model = models.chatbot.ChatbotModel(vocab_size=FLAGS.vocab_size,
  File "/home/sysadmin/anaconda3/bin/3.6/bin/3.6/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 50, in __getattr__
    raise AttributeError(name)
AttributeError: vocab_size

Please resolve this issue at the earliest.

Thanks in advance

**Comment by domerin0** [comment] 2018-03-30 14:42
Hi, sorry I hadn't realized I missed this issue. While I'm sure you have moved on to another thing, I am aware of this problem. (see #issue23). I have been extremely busy and unable to regularly work on open source project for several months now. I am hoping to change that, but until then I won't be able to fix this issue. 

I am closing this since it is a duplicate of the issue I linked earlier, but feel free to open another issue, or comment  here or there.

**Closed as completed by domerin0** 2018-03-30 14:42 UTC
